services:
  app:
    build:
      context: .
    depends_on:
      - migrate
    ports:
      - 8080:8080
  db:
    image: postgres
    # volumes:
    #   - db:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      retries: 5
    ports:
      - "${DB_PORT}:5432"
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable",
        "up",
      ]
    depends_on:
      db:
        condition: service_healthy
# volumes:
#   db:
